### ISSUE TITLE
Need Underground Village mod?

### ISSUE THREAD

**Issue by KCtops6** [Reggarfgod/create_better_villagers#2]
Hello, the latest version of the mod seems to need the Underground Village mod.  I am a modpack author for the "Infinite Horizons - Modded Superflat Survival" modpack and that mod would be useless in the pack.  From the changelog, I am not sure if this was intended behavior.  Thank you for your time.

**Comment by electricsteve** [comment]
I am facing this same issue I have with this mod. I find it scummy to add one of your other mods as a required dependency that isn't required. Now I do not know the reason for this, but I suspect it's because @Reggarfgod wants to increase the download count of that mod.
